# Generated by Django 4.1.7 on 2023-03-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_number', models.AutoField(primary_key=True, serialize=False)),
                ('session', models.IntegerField(default=0)),
                ('participants', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(default='', max_length=50)),
                ('group_number', models.IntegerField(default=0)),
                ('session', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='session',
            name='id',
        ),
        migrations.AddField(
            model_name='session',
            name='participants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='session_number',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
