# Generated by Django 4.1.7 on 2023-03-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0003_bid_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='auction_one',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='group',
            name='auction_three',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='group',
            name='auction_two',
            field=models.CharField(default='', max_length=50),
        ),
    ]
