# Generated by Django 4.1.7 on 2023-03-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0004_group_auction_one_group_auction_three_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.IntegerField(default=0)),
                ('block', models.IntegerField(default=0)),
                ('winner', models.CharField(default='', max_length=50)),
                ('maxoffer', models.IntegerField(default=0)),
                ('secondoffer', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='auction_one',
        ),
        migrations.RemoveField(
            model_name='group',
            name='auction_three',
        ),
        migrations.RemoveField(
            model_name='group',
            name='auction_two',
        ),
        migrations.AddField(
            model_name='bid',
            name='group_number',
            field=models.IntegerField(default=0),
        ),
    ]
