# Generated by Django 4.1.7 on 2023-03-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0005_winner_remove_group_auction_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(default='closed', max_length=10),
        ),
    ]
