# Generated by Django 4.1.7 on 2023-04-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0006_session_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='bdm_one',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='bdm_two',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='condition',
            field=models.CharField(default='', max_length=5),
        ),
    ]
