# Generated by Django 4.1.7 on 2023-04-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0007_group_bdm_one_group_bdm_two_group_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='reward',
            field=models.IntegerField(default=0),
        ),
    ]
