# Generated by Django 4.1.7 on 2023-04-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0008_participant_finished_participant_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='charity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='winner',
            name='completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='winner',
            name='reward',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='winner',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
