# Generated by Django 4.1.7 on 2023-06-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0011_alter_participant_finished_alter_winner_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
