# Generated by Django 4.1.7 on 2023-11-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0013_delete_bid_delete_winner_remove_group_bdm_one_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pairNumber', models.IntegerField(default=0)),
                ('roundNumber', models.IntegerField(default=0)),
                ('took', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('pairNumber', models.AutoField(primary_key=True, serialize=False)),
                ('session', models.IntegerField(default=0)),
                ('condition', models.CharField(default='', max_length=20)),
                ('roleA', models.CharField(default='', max_length=50)),
                ('roleB', models.CharField(default='', max_length=50)),
                ('preparedA', models.BooleanField(default=False)),
                ('preparedB', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pairNumber', models.IntegerField(default=0)),
                ('decision', models.IntegerField(default=0)),
                ('response', models.CharField(default='', max_length=10)),
                ('message', models.IntegerField(default=0)),
                ('money', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='pairNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='role',
            field=models.CharField(default='', max_length=1),
        ),
    ]
