# Generated by Django 4.1.7 on 2023-11-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0014_decision_pair_response_participant_pairnumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='id',
        ),
        migrations.AddField(
            model_name='group',
            name='winning_block',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='finished_fourth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='id_number',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='reward_in_fourth',
            field=models.IntegerField(default=0),
        ),
    ]
