# Generated by Django 4.1.7 on 2023-11-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0015_remove_participant_id_group_winning_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='id_number',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
