# Generated by Django 4.1.7 on 2023-11-26 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0017_remove_participant_id_number_participant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='lastprogress',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='participant',
            name='screen',
            field=models.IntegerField(default=0),
        ),
    ]
