# Generated by Django 4.1.7 on 2023-11-26 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0018_participant_lastprogress_participant_screen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='lastprogress',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
