# Generated by Django 5.1.1 on 2025-04-17 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0020_outcome_delete_decision_delete_response_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Outcome',
        ),
        migrations.DeleteModel(
            name='Pair',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='group_number',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='paidtoken',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='pair3',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='pair4',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='pair5',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='pair6',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='session',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='token',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='winning_block',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='winning_trust',
        ),
    ]
